### PR TITLE
Traffic Register Search Directory Update CSS

### PR DESCRIPTION
**Pull request by ChrispinP**
- Directory Button styling
- Remove experimental code
- Remove code for pages that no longer exist such as Reviewer Dashboard and old Reg Doc Builder 
- Disable Back Links for Draft Builder & Task Board
- Remove Background where Reg Doc ID is displayed in the Draft Builder, Draft Editor, & Print Page 
- Remove Background for Welcome Name on Task Board

### CODE REVIEW

**Review by dianamartin — CHANGES_REQUESTED** [review]
@ChrispinP Hey, for line 10 - I thought we weren't going to keep the "golden" icon for the Regs?

**Comment by ChrispinP** [comment]
@dianamartin for the goldenrod styling I can remove it if we decide icons should never not be black. I thought it would be a fun thing to show stakeholders. Alternatively we could keep it in code even if we dont apply it, similarly to fa-top or fa-bot which are rarely applied. Thoughts?

**Comment by dianamartin** [comment]
I don't think I'm familiar with the fa-top or fa-bot (is that top/bottom?)

**Comment by ChrispinP** [comment]
Correct. fa-top shifts the icon to touch the top of the line, fa-bot to rest on the bottom of the line. By default we align our icons to the middle.

**Pull request merged**
